### ISSUE TITLE
Different font size on Validate Data with ShEx

### ISSUE THREAD

**Issue by ulitol97** [weso/rdfshape-client#16]
There is a slight difference in the font size of the editors in the ShEx validation section.

![Untitled](https://user-images.githubusercontent.com/35763574/71996184-15007700-323c-11ea-99a6-cfc1258e4fc9.png)

**Comment by labra** [comment]
Indeed, I noticed that but I have no idea how to take control on the fonts. 

One thing I tried to do is to recover the codemirror instance object that lies behind YaTe and YaShE...

I think it will be possible to assign a specific size to that codeMirror object as described [in the codeMirror API documentation](https://codemirror.net/doc/manual.html#api_sizing). 

Another possibility could be to play with the CodeMirror.css file as [described here](https://codemirror.net/doc/manual.html#styling) but I am not sure if it will solve it.

I tried to play a little bit with those options without success...if you try, take into account that you may need to call `cm.refresh()` after a change.

**Comment by mistermboy** [comment]
I think there is no way to change the font size with the codemirror instance object but you can change it with the css:

.CodeMirror {
      font-size: 26px !important;
}

**Comment by ulitol97** [comment]
Thanks! I had thought about that... I guess that will do, if there is not a more elegant solution 👍

**Comment by labra** [comment]
I merged and deployed it to [rdfshape.weso.es](http://rdfshape.weso.es) and it seems to work. 🎉
