### ISSUE TITLE
Permalink to visualize RDF data seems to fail for medium-size files

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-client#32]
When trying to visualize some medium size RDF data like [this](https://github.com/labratests/aflux/blob/main/theodore.ttl), the permalink option doesn't seem to work. 

The problem may be that the generated URL is longer than expected but if that is the case, some nice error message would be better than the current behaviour.

**Comment by ulitol97** [comment]
This is due to limitations with the free shortener service, as mentioned in #26. The server should not return a 400 error in those cases, I'll look into it.

**Comment by ulitol97** [comment]
I've reduced the chance of triggering this issue. In [https://github.com/weso/rdfshape-client/pull/36](https://github.com/weso/rdfshape-client/pull/36) I disabled the permalink option when validating data by file or **when the text provided is too long** to form a valid URL:


> ![img](https://user-images.githubusercontent.com/35763574/100369238-f3031500-3004-11eb-8fb6-270b937b3b8f.png) 
---

As for the possibility of showing a prettier error message, I find it difficult. Right now we're serving the front-end with express (nodejs) and, as stated [here](https://stackoverflow.com/questions/54121191/express-js-server-400-bad-request-error-for-a-long-url-get-request), the max request size is not something worth messing with.


Regarding the error itself, there is not much more we can do, any page will respond with an error if given a long enough URL ([example](https://google.es?dummy=https://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeThttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMaphttps://rdfshape.weso.es/shExValidate?activeSchemaTab=%23schemaTextArea%26activeTab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMapab=%23dataTextArea%26data=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3Aalice%20%3Aname%20%22Alice%20Cooper%22%20%3B%20%3Aage%2023%20.%0A%3Abob%20%20%20%3Aname%20%22Robert%22%3B%20%3Aage%20%3Aunknown%20.%26dataFormat=TURTLE%26dataFormatTextArea=TURTLE%26endpoint=%26inference=None%26schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%3AUser%20%7B%0A%20%3Aname%20xsd%3Astring%20%3B%0A%20%3Aage%20%20xsd%3Ainteger%0A%7D%26schemaEmbedded=false%26schemaEngine=ShEx%26schemaFormat=ShExC%26schemaFormatTextArea=ShExC%26shapeMap=%3Aalice%40%3AUser%2C%20%3Abob%40%3AUser%26shapeMapActiveTab=%23shapeMapTextArea%26shapeMapFormat=Compact%26shapeMapFormatTextArea=Compact%26triggerMode=shapeMap)).

**Comment by ulitol97** [comment]
Closing since the front-end prevents the user from creating invalid permalinks and the permalink service we're using is now our own and returns more detailed errors.
