### ISSUE TITLE
The UML visualization generated by XMI doesn't show the full diagram

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-client#40]
When visualizing a medium size diagram like [this one](https://github.com/kg-subsetting/biohackathon2020/blob/main/use_cases/genewiki/genewiki.shex), half of the diagram generated can't be seen.

**Comment by jorgealvarezfidalgo** [comment]
Seems like a PlantUML limitation, since we are just showing its output. Inspecting the original, PlantUML is setting a max width of 2000 px to the image generated, regardless of the content. Therefore, those diagrams which tend to be expanded horizontally are cut short.

It is an issue that must be solved in _shumlex_ itself, although i'm unsure of the way. Doesn't seem like the PUML code allows for an increase in size. This may take some time, more than it initially seemed.

**Comment by jorgealvarezfidalgo** [comment]
### Sobre los progresos realizados

El proceso de creación de diagramas mediante Mermaid resulta algo engorroso por la cantidad de caracteres que nosotros empleamos (<>:~...) que esto no acepta. A base de emplear sustitutos y reemplazarlos dinámicamente, conseguimos mantenerlo.

No obstante, el resultado final parece una mejoría. Un SVG que nos permite copiar los textos que contiene, que podemos descargar como SVG o PNG (presuntamente) y en principio, configurable en cuanto a temas estilísticos.

![imagen](https://user-images.githubusercontent.com/47144679/99654139-359f7d00-2a5a-11eb-9e74-586ada6ced62.png)

En cuanto al diagrama que ocasionó el caos, he de solucionar un par de minucias, pero aquí lo tenemos en su completitud. De algún modo, he de determinar dinámicamente la magnitud del diagrama para ajustar el tamaño del SVG respecto a su contenedor y así, hacerlo legible.

![imagen](https://user-images.githubusercontent.com/47144679/99653927-f2450e80-2a59-11eb-84cb-27c09a5ddcb5.png)

Con tal cantidad de relaciones que posee, es algo farragoso, pero me parece que usemos lo que usemos, eso es dificilmente evitable.

_Originally posted by @jorgealvarezfidalgo in https://github.com/weso/shumlex/issues/14#issuecomment-730281279_

**Comment by labra** [comment]
Una posibilidad a estudiar sería mostrar dinámicamente el diagrama de forma configurable y bajo demanda del usuario. 

Por ejemplo, podría mostrarse solamente una de las entidades y los vecinos con un botón que indique que hay más clases y que al pulsarlo las mostrase. Una visualización muy chula es [ésta](https://apis.guru/graphql-voyager/). En [este artículo](https://www.freecodecamp.org/news/how-we-got-1-500-github-stars-by-mixing-time-tested-technology-with-a-fresh-ui-b310551cba22/) explica las tecnologías que usaron.

Algunas librerías de visualización de grafos que se podrían explorar son [vis.js](https://visjs.org/), [d3.js](https://d3js.org/), [Cytoscape](https://cytoscape.org/), etc...

**Comment by jorgealvarezfidalgo** [comment]
Ah, esa es una fantástica idea. Coincido que estos diagramas grandes no aportan gran cosa, más allá de confusión. Decididamente, necesitan un mecanismo que haga su estudio más claro... Me gusta lo que planteas y veré si puedo conseguir algo similar.

Vamos por partes, no obstante. Primero, que genere un SVG para todas las características que soportamos. Tras acabar eso, abriré una nueva Issue a ese respecto.

By the way, I copied my last comment from the other repo did not intend to disrupt the language adopted here. So, a translation:

Ah yes, that's an excellent idea. I agree; those large diagrams do not contribute much beyond some confusion. Indeed, a mechanism which eases its study is necessary. I like your input and I will look for a similar solution.

Nonetheless, let's keep it straight. Firstly, to generate any SVG according to the supported features. Then, a new issue on this matter shall be opened.

**Comment by jorgealvarezfidalgo** [comment]
Later than I would have liked, but I have resolved this issue in my fork by integrating the new Shumlex version. It now makes use of SVG to show the UML class diagram, allowing for its download as well.
![imagen](https://user-images.githubusercontent.com/47144679/103711499-dec51700-4fb7-11eb-9bf8-e7f4f088d007.png)

It feels somewhat constrained in that space. Maybe it would be better if we placed it in the next row, so it could make use of the full width?

Besides that possible modification, I'll try to implement a download option for the graph before pull requesting.

**Comment by labra** [comment]
One possibility is to allow the different windows/panes in RDFShape to be customizable by the user, i.e. that a user could change the resize the windows as he wants. 

It would be even greater if we could offer other options on those windows/panes similar to a desktop application. 

We have already a issue for resizing the windows [here](https://github.com/weso/rdfshape-client/issues/41)

**Comment by labra** [comment]
I noticed now that the YaSHE window (the editor of ShEx) already supports to increase the size of the editor to fit the whole browser window. Maybe a similar functionality could more easily be added to the SVG visualizer window?

**Comment by jorgealvarezfidalgo** [comment]
Well, here's my take on that. Similarly to what's offered in Yashe, a quickly implemented fullscreen function.
![imagen](https://user-images.githubusercontent.com/47144679/103770185-e28f8280-5025-11eb-83da-0fb677019b0b.png)

![imagen](https://user-images.githubusercontent.com/47144679/103770198-e7543680-5025-11eb-9ed5-f401343d69d8.png)
Of course, our old friend Genewiki isn't as pretty, but it is a much better option to contemplate it.
![imagen](https://user-images.githubusercontent.com/47144679/103770311-136fb780-5026-11eb-8073-90b5f5693b0b.png)

Did it for the graph as well.
![imagen](https://user-images.githubusercontent.com/47144679/103770356-2da99580-5026-11eb-96e6-a8ad7c44a72c.png)

![imagen](https://user-images.githubusercontent.com/47144679/103770419-43b75600-5026-11eb-80af-94f8565aa786.png)

Which may be now downloaded with the current layout displayed.
![imagen](https://user-images.githubusercontent.com/47144679/103770503-66496f00-5026-11eb-830e-6e28ccc12ec0.png)

Any suggestions? I think that's pretty much it for now.

**Comment by labra** [comment]
That looks quite good. I think the only possibility would be to be able to allow the user to move the positions of the generated boxes to whichever position he chose or try to work on the visualization that shows a main shape and its inmediate neighbours on demand, but I understand that those are more long term changes. You may open a new issue for each of those approaches as future work and deploy the new functionality as is for now...I would really like to play with it as soon as possible 😄
