### ISSUE TITLE
Change label of "Shapes graph" in ShEx

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-client#85]
The input label for ShEx schemas in RDFShape is "Shapes graph". While that terminology is OK for SHACL, in the case of ShEx, it is called Schema. 

If those labels are separate, it would be better to ask for "Schema" or "ShEx schema" in the case of ShEx.

In the case of SHACL, it can remain as "Shapes graph" because that's the terminology used in SHACL

**Comment by ulitol97** [comment]
For ShEx, the text has been changed from `Shapes Graph (ShEx)` to `Schema (ShEx)`
